netdisco/const.py, netdisco/discoverables/__init__.py, netdisco/discoverables/plex_mediaserver.py, netdisco/discovery.py, netdisco/gdm.py
Hi Balloob,
This PR introduces 'GDM' support.
It's an auto-discovery method like SSDP, made by Plex.
I'd like to use this to autodiscover plex media servers in HA, similar as Hue discovery is done now.
Hope you like
=> Initial commit of GDM discovery support

netdisco/const.py, netdisco/discoverables/logitech_mediaserver.py, netdisco/discovery.py, netdisco/lms.py
Simple combination of the discovery code submitted to home-assistant by @molobrakos in balloob/home-assistant#1561 and the existing Plex media server support code, fixes #10.
=> Add discovery for local Logitech Media servers.

netdisco/const.py, netdisco/discoverables/panasonic_viera.py
this pr adds support for discovering panasonic viera tv devices
=> add support for panasonic viera tv

netdisco/tellstick.py
closes https://github.com/home-assistant/netdisco/issues/22
=> Manually close socket cant "with" in py 2.7

netdisco/ssdp.py
Improve error handling when trying to bind to available interfaces. If not able to bind to any available interface will bind to `0.0.0.0`, if that fails too, print a warning and return an empty list.
Fixes #25
=> Handle SSDP interface bind errors

netdisco/discoverables/roku.py
**Output (python3 -m netdisco)**
Discovered devices:
*roku [('192.168.1.100', 8060)]*
sabnzbd []
kodi []
google_cast [('192.168.1.102', 8009)]
philips_hue [('Philips hue (192.168.1.9)', 'http://192.168.1.9:80/')]
=> Added support for roku

netdisco/util.py
I guess that this is related to PyLint 1.6.x
=> Update pylint disable

netdisco/discoverables/DLNA.py, netdisco/discoverables/belkin_wemo.py, netdisco/discoverables/google_cast.py, netdisco/discoverables/kodi.py, netdisco/discoverables/logitech_mediaserver.py, netdisco/discoverables/netgear_router.py, netdisco/discoverables/panasonic_viera.py, netdisco/discoverables/philips_hue.py, netdisco/discoverables/plex_mediaserver.py, netdisco/discoverables/roku.py, netdisco/discoverables/sabnzbd.py, netdisco/discoverables/sonos.py, netdisco/discoverables/tellstick.py, netdisco/discoverables/webos_tv.py, netdisco/discovery.py, netdisco/lms.py, netdisco/mdns.py, netdisco/service.py, netdisco/ssdp.py, netdisco/tellstick.py, netdisco/util.py, setup.py
First round, still plenty of room to improve.
=> Update/add docstrings for PEP 257

netdisco/const.py, netdisco/discoverables/mystrom.py
Discover [myStrom](https://mystrom.ch) switches.
```bash
mystrom [('Switch-01276f', 'http://10.100.0.137', '64:00:2d:01:27:6f')]
```
=> Discover myStrom devices

netdisco/discoverables/directv.py
Example output:
directv [('10.10.130.1', 'RID-02520980xxxx')]
=> Add Support for DirecTV Receivers

netdisco/discoverables/__init__.py
This works around issue #46.
Signed-off-by: Anton Lundin <glance@acc.umu.se>
=> Return host on ip convertion error

netdisco/const.py, netdisco/discoverables/bose_soundtouch.py
This commit add support for Bose SoundTouch discovery using MDNS.
=> Add Bose SoundTouch discovery support

netdisco/discoverables/samsungac.py, netdisco/discovery.py, netdisco/samsungac.py
This PR allows to discover Samsung Smart Air Conditioners
=> Add support for Samsung Smart Air Conditioner

netdisco/ssdp.py
Speed up SSDP discovery by not calling scan twice (which effectively made the discovery timeout being 2*DISCOVER_TIMEOUT).
Move the hack for wemo ST_ROOTDEVICE into the scan function.
Please note that since I have no wemo, I have not been able to verify that this does not break wemo functionality. I have verified that other SSDP services seem to work fine.
=> Speed up SSDP discovery

netdisco/discoverables/denonavr.py
This is support for Denon AVR receivers I recently added to home-assistant. It is working with SSDP discovery as it is.
=> Added support for Denon AVR receivers

netdisco/discoverables/logitech_mediaserver.py, netdisco/lms.py
Discover the port number for the web interface for the LMS. Needed for https://github.com/home-assistant/home-assistant/pull/5084
=> Discover LMS web server port

netdisco/discoverables/yeelight.py
This PR is all the work from @rytilahti, the only changes I've made are the linting fixes that are required before the merge gets approved.
See https://github.com/home-assistant/netdisco/pull/77 for more details
=> Yeelight support

netdisco/const.py, netdisco/discoverables/frontier_silicon.py
For Internet Radios like Hama, Medion, Auna ...
=> Added discovers for Frontier Silicon devices

netdisco/discoverables/apple_tv.py
It's good to know where to connect...
=> Add missing host field to Apple TV

netdisco/philips_hue_nupnp.py
Hue: Catch (and ignore) any exception raised (keeps logs clean)
=> Hue: Catch any exception raised (keeps logs cleaner)

netdisco/discovery.py, netdisco/service.py
Remove `limit_discovery` because it did not work and it was not being used.
=> Remove limit_discovery

netdisco/philips_hue_nupnp.py, netdisco/ssdp.py, setup.py
Add timeouts to Hue and SSDP requests to make sure that we don't block indefinitely.
=> Add timeouts

netdisco/const.py, netdisco/discoverables/__init__.py, netdisco/discoverables/harmony.py
Adds discovery support for the Harmony Hub remote
=> Add discovery for Harmony Hub

requirements.txt
=> Upgrade zeroconf

netdisco/discoverables/spotify_connect.py
Add support for discovering Spotify Connect devices.
=> Add support for discovering spotify connect

netdisco/discoverables/ikea_tradfri.py
Discover IKEA Tradfri gateways
=> Discover Ikea Tradfri

netdisco/discoverables/apple_tv.py, setup.py
Update the AppleTV output to use the base dictionary.
=> Update apple tv output

netdisco/discoverables/__init__.py, setup.py
This uses the method by @postlund to get the IP address of the hostname for mDNS discoverables. Also bumping the version to 1.0.0rc3
=> Change mdns host resolve

netdisco/ssdp.py
SSDP contained a bunch of functionality that we didn't use. Removing it 👍
=> Simplify SSDP discovery

MANIFEST.in
=> Add license and readme file to source tarball

netdisco/discoverables/octoprint.py
Support for discovering OctoPrint servers.
=> Support for OctoPrint

netdisco/discoverables/wink.py
Support for Finding Wink hubs v1, v2 and the Wink relay.
=> Added support for Wink

netdisco/discoverables/yeelight.py
Reverts home-assistant/netdisco#151
Per https://github.com/home-assistant/netdisco/pull/151#issuecomment-335280982
=> Revert "detect yeelight's ceiling lamp"

netdisco/const.py, netdisco/discoverables/ziggo_mediabox_xl.py
Support for the Dutch Ziggo Mediabox XL device.
Also see: https://github.com/home-assistant/home-assistant/pull/10514
=> Add Ziggo Mediabox XL support

netdisco/discoverables/yeelight.py
Adds discovery of Yeelight Bedside Lamp (Wifi + Bluetooth version).
=> Add Yeelight Bedside Lamp support

netdisco/discoverables/fritzbox.py
Add support for AVM FRITZ devices discovery
=> add AVM FRITZ devices support

netdisco/discoverables/hp_printer.py
Add support for HP printer discovery
=> add HP printers support

netdisco/discoverables/volumio.py
Add discovery of Volumio devices.
=> add volumio discovery

netdisco/daikin.py
=> Fix reuse of UPNP UDP port in NAS may fail.

setup.cfg
No need for that as the project is Python >= 3 only.
=> Don't bother shipping a universal wheel

netdisco/discoverables/hass_mobile_app.py
=> Add hass mobile app detection

netdisco/mdns.py
I sent the wrong squash on the first go
=> Fix mdns discovery
