netdisco/discoverables/belkin_wemo.py
Needed for pywemo 0.3.2, and for this fix https://github.com/balloob/home-assistant/issues/476
=> Add MAC address to wemo discovery attributes

netdisco/discoverables/belkin_wemo.py
Some early Wemo firmware doesn't return the mac address - this PR handles this without throwing an exception.
=> Handle mac address missing in early wemo firmware.

netdisco/discoverables/belkin_wemo.py, setup.py
balloob/home-assistant#1453 adds a serial number to uniquely identify WeMo devices. This updates netdisco to provide the same information when it discovers a WeMo device.
=> Add serial number to wemo discovery info

netdisco/ssdp.py
Sending an M-SEARCH request with MX: 0 crashes random uPNP listeners.
- Cisco EPC3925 (balloob/home-assistant#1557)
- Netgear router (@BryonCLewis on home-assistant gitter)
- Old Roku clients (http://forums.roku.com/viewtopic.php?p=523858&sid=daad2638e2622bcce868e89497930fad)
=> Fix uPNP ping of death packet.

netdisco/ssdp.py, netdisco/util.py, requirements.txt, setup.py
This fix was needed for SSDP discovery on Windows 10 (pavoni/pywemo#23).
Proposing it as a PR here because the code is basically identical.
Not sure if similar fixes are needed for gdm (also multicast) and lms (broadcast), but I don't have Windows systems to test on.
=> Bind sockets to interface addresses when sending ssdp requests

netdisco/discoverables/tellstick.py, netdisco/discovery.py, netdisco/tellstick.py
Add discovery of Tellstick Net devices (http://www.telldus.se/products/tellstick_net).
Tellstick Net devices can receive commands and also be asked for sensor updates on the local network. For Tellstick Net devices on the same network as the client, this will make it possible for faster and connectivity-independent updates than by using the Telldus Live online service.
=> Add support for discovery of Tellstick Net devices

netdisco/ssdp.py
Returned data on socket might contain non-ascii values in scan.
File "/.../netdisco-0.6.1-py3.5.egg/netdisco/ssdp.py", line 235, in scan
response = sock.recv(1024).decode("ascii")
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 53: ordinal not in range(128)
I had nothing but ascii in the output from python -m netdisco, but there was obviously something in the packets...
MiniDLNA sent DATE localized...
=> sock.recv(1024).decode("utf-8") instead of "ascii"

netdisco/ssdp.py
Now that we use multiple sockets during discovery, we should not abort discovery whenever we hit a socket error. (#25)
=> Gracefully handle socket errors during SSDP discovery.

netdisco/gdm.py
The switch to UTF-8 allows localized name for services.
```bash
plex_mediaserver [('medià', 'https://10.100.0.31:32400')]
```
Plex let one set a name like in the output above.
=> Switch to utf-8 for data (fixes #32)

netdisco/const.py, netdisco/discoverables/home_assistant.py
Thanks to the [zeroconf component](https://home-assistant.io/components/zeroconf/) Home Assistant is discoverable.
```bash
home_assistant [('http://10.100.0.197:8123', '0.24.0.dev0', True)]
```
=> Discover Home Assistant instances

netdisco/discoverables/yamaha.py
It turns out that on yamaha receivers the discovered port (typically
port 8080) for the desc.xml *is not* actually active for the control
url, which is typically sitting on port 80 (and is expressed with the
yamaha:X_URLBase field).
This is a bit more strict about using that field to build up the
control url.
It also returns model_name which the rxv code asks for. This allows
the netdisco discovery to be a full replacement for the ssdp code in
rxv at least as far as home-assistant is concerned, and should enable
yamaha via the discovery component.
=> fix ctrl url discovery

netdisco/discoverables/yamaha.py
When discovering zones for the yamaha receiver, we are actually
probing the xml of the yamaha specific desc.xml, which provides all
the function details of the system (it's kind of soap-esque dump). The
generic desc.xml isn't good enough, and if we use that we don't end up
with any receivers discovered because no zones are found.
=> final fix for yamaha discovery

netdisco/__main__.py, netdisco/daikin.py, netdisco/discoverables/samsungac.py, netdisco/discovery.py, netdisco/gdm.py, netdisco/lms.py, netdisco/samsungac.py, netdisco/ssdp.py, netdisco/tellstick.py
The Samsung AC discovery runs on port 1900 which is occupied by a lot of systems for upnp. Caused anyone with a synology to run into issues.
#66 might be a fix but we will need @sfam to confirm that it still works for him and will need @jaharkes to confirm that it still works on synology.
=> Disable Samsung AC scanning

netdisco/discovery.py
Run all discovery scan() functions in separate threads to parallelize and speed up initial detection.
=> Speed up initial discovery

netdisco/discoverables/__init__.py, netdisco/discoverables/kodi.py, netdisco/discoverables/sabnzbd.py
Kodi and SABnzbd returned is_discovered() as true even if there are no such devices present, as long as an mDNS '_http._tcp.local.' entity is present on the network.
=> Fix empty lists for Kodi and SABnzbd

netdisco/const.py, netdisco/discoverables/samsung_tv.py, netdisco/ssdp.py
Add support for discovering Samsung Smart TV which are able to be controlled by the Samsung Remote Control protocol.
Ad-hoc tested on two models from series D and E.
=> Discover Samsung Smart TV

netdisco/const.py, netdisco/discoverables/homekit.py, netdisco/discoverables/yeelight.py, netdisco/lms.py
For the upcoming netdisco 1.0, we want to move the entry info objects to be all dictionaries. This PR will update all current protocols that return a dict to use standardized keys.
=> Standardize entry dict

netdisco/discoverables/openhome.py
This PR adds support for discovering Openhome compliant devices (http://openhome.org/) such as Linn Ds.
=> Add openhome devices as discoverable

netdisco/discoverables/yeelight.py
Properties are returned as bytes, which makes error when recorded tries to json encode contents of the entry.
=> yeelight: decode properties to utf-8

netdisco/samsungac.py
Fixes a crash when something else is also listening on the upnp port.
=> Reuse Address for Samsung AC Discovery

netdisco/discoverables/frontier_silicon.py
My Canon printer does not broadcast ST so netdisco gives in exception in frontier_silicon.py for me:
```
$ python3 -m netdisco
Discovered devices:
Traceback (most recent call last):
File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/runpy.py", line 170, in _run_module_as_main
"__main__", mod_spec)
File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/runpy.py", line 85, in _run_code
exec(code, run_globals)
File "/Users/postlund/git/netdisco/netdisco/__main__.py", line 32, in <module>
main()
File "/Users/postlund/git/netdisco/netdisco/__main__.py", line 22, in main
for dev in netdisco.discover():
File "/Users/postlund/git/netdisco/netdisco/discovery.py", line 96, in discover
return [dis for dis, checker in …
```
=> Check that ST exists for UPnP device in frontier silicon

netdisco/const.py, netdisco/discoverables/apple_tv.py
Will find Apple TVs with home sharing enabled and publish HSGID and device name.
=> Add Apple TV support

.gitignore, netdisco/discoverables/flux_led.py, netdisco/discovery.py, netdisco/flux_led.py, netdisco/util.py, requirements.txt, setup.py, tox.ini
This change adds support for [Fluxled](https://home-assistant.io/components/light.flux_led/) device discovery.
It is partly based on the Tellstick class and the `flux_led` python module: https://github.com/Danielhiversen/flux_led/blob/b48a1b53390360f61fe35a37cc46c948a3a8cb26/flux_led/__main__.py#L957-L1018
But instead of using broadcast, this implementation determines the local networks and sends an UDP query to every possible device on these networks. This more closely matches the method used by the 'Magic Home' app which is the official app for these devices. In my experience (tested on a Arilux RGB controller) broadcast offered bad/flaky discovery with no easy way to improve (multiple send/receive tries, longer timeout, etc).
I have yet to investigate how to make netdisco register …
=> Add Fluxled discovery.

netdisco/discoverables/philips_hue.py, netdisco/discovery.py, netdisco/philips_hue_nupnp.py
Philips Hue bridge limits how many SSDP lookups you can make. If you
make two consecutive SSDP lookup requests, there won't be any Philips
Hue bridges found in the second lookup attempt.
To work around this Philips recommends to do N-UPnP lookup
simultaneously with SSDP lookup: https://developers.meethue.com/documentation/hue-bridge-discovery
We came across this issue while working on a project that uses Home
Assistant. The Philips Hue bridge was discovered in the morning but
after restarting Home Assistant later it wouldn't get discovered
anymore.
=> Implement N-UPnP Philips Hub discovery

netdisco/philips_hue_nupnp.py
This change clears the 'entries' list in the Philips Hue scanner to prevent the entries list from continually growing, causing a memory leak.
Resolves https://github.com/home-assistant/home-assistant/issues/6239, https://github.com/home-assistant/home-assistant/issues/6165
=> Fix memory leak by clearing list of Philips Hue bridges on scan

netdisco/ssdp.py
I found a device on our network which includes additional directives in the `cache-control` header. Specifically the `cache-control` header contained:
`no-cache="Ext", max-age = 5000`
I found the scan failed as it tried to cast `"Ext"` to an int. This PR uses a regex to extract `max-age` directives first and calculate from there.
=> Extract only max-age from cache-control header

netdisco/discoverables/philips_hue.py
#99 made sure we cleared the nupnp_entries. There was another leak where it would add all the SSDP Hue entries back to the nupnp one so they would not get garbage collected.
=> Fix another Hue memory leak

netdisco/mdns.py
Fix on windows:
```
17-03-05 19:35:10 ERROR (MainThread) [homeassistant.core] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
File "/mnt/d/Fork/home-assistant/homeassistant/components/discovery.py", line 128, in _discover
netdisco.scan()
File "/mnt/d/Fork/test-env/lib/python3.4/site-packages/netdisco/discovery.py", line 53, in scan
self.mdns.start()
File "/mnt/d/Fork/test-env/lib/python3.4/site-packages/netdisco/mdns.py", line 20, in start
self.zeroconf = zeroconf.Zeroconf()
File "/mnt/d/Fork/test-env/lib/python3.4/site-packages/zeroconf.py", line 1660, in __init__
self._listen_socket = new_socket()
File "/mnt/d/Fork/test-env/lib/python3.4/site-packages/zeroconf.py", line 1619, in new_socket
s.setsockopt(socket.SOL_SOCKET, reuseport, 1)
OSError: …
```
=> Bugfix exception on close on windows linux subsystem

netdisco/discoverables/samsung_tv.py
Samsung TVs were being discovered 4 times. Now it's 1.
=> Fix Samsung discovery to only discover once

netdisco/__main__.py, netdisco/const.py, netdisco/discoverables/__init__.py, netdisco/discoverables/apple_tv.py, netdisco/discoverables/belkin_wemo.py, netdisco/discoverables/denonavr.py, netdisco/discoverables/directv.py, netdisco/discoverables/harmony.py, netdisco/discoverables/hass_ios.py, netdisco/discoverables/home_assistant.py, netdisco/discoverables/homekit.py, netdisco/discoverables/kodi.py, netdisco/discoverables/netgear_router.py, netdisco/discoverables/openhome.py, netdisco/discoverables/panasonic_viera.py, netdisco/discoverables/philips_hue.py, netdisco/discoverables/plex_mediaserver.py, netdisco/discoverables/roku.py, netdisco/discoverables/sabnzbd.py, netdisco/discoverables/samsung_tv.py, netdisco/discoverables/sonos.py, netdisco/discoverables/webos_tv.py, netdisco/discoverables/yamaha.py, netdisco/discoverables/yeelight.py, netdisco/philips_hue_nupnp.py, netdisco/util.py, requirements.txt, setup.py, tests/discoverables/test_yamaha.py
This simplifies the code, cleans up unnecessary code paths and ensures that `info_from_entry` always returns a dictionary.
Fixes #72
This will require us to go through all the discoverable components and platforms in Home Assistant and make sure that they expect `discovery_info` to be a dictionary.
=> Version 1.0: Simplify code and return dictionaries

netdisco/discoverables/lutron.py
Adding support for Lutron Caseta Smart Bridge and Smart Bridge Pro, which support mDNS for discovery.
Here is sample output from netdisco:
```
lutron:
[{'host': '192.168.2.11',
'hostname': 'Lutron-a0f6fdXXXXXX.local.',
'port': 22,
'properties': {'CODEVER': '04.03.05f000',
'DEVCLASS': '08050100',
'FW_STATUS': '1:NoUpdate',
'MACADDR': 'a0:f6:fd:XX:XX:XX',
'NW_STATUS': '11:InternetWorking',
'ST_STATUS': 'good'}}]
```
Lutron may also be using mDNS for the Lutron Connect Bridge (CONNECT-BDG2) for RadioRA 2 and/or the Staples Connect hub, but I only have the Smart Bridge Pro 2 for testing. When discovery is implemented in Home Assistant for Lutron Caseta, it should check the **DEVCLASS** property for a compatible device.
For reference purposes, here is a table of the DEVCLASS values for Lutron …
=> Add Lutron Caseta discovery

netdisco/discoverables/__init__.py
If mDNS properties include a "mac" key, set top-level ATTR_MAC_ADDRESS
info property for consistency.
This property for example is available for Yeelight lights.
=> MDNSDiscoverable: Set ATTR_MAC_ADDRESS if available.

netdisco/discoverables/xiaomi_gw.py
Uses mDNS discovery. There appears to be a case of mDNS properties
misparsing for the Gateway, so workaround for that is added, to
properly return ATTR_MAC_ADDRESS (might be useful to support
multiple gateways).
=> Add Xiaomi Mi Home Gateway discovery.

netdisco/gdm.py
This fixes `OSError: [Errno 22] Invalid argument` on OpenBSD
It follows suggestion at https://bugs.python.org/issue23127
=> use the extended signature of the setsockopt

netdisco/daikin.py, netdisco/lms.py, netdisco/ssdp.py, netdisco/tellstick.py
A number of services (SSDP, Daikin, etc.) use foreground scan approach,
which means scans are sequential and there times add up, leading to a
long discovery cycle.
This negatively affects user experience of project using NetDisco, e.g.
HomeAssistant. With the original 5s timeout, it takes ~30s for devices
to be discovered after HA startup. As initial acquaintance/setup requies
regular restarts, such delay lead to persistent subjective impression
that HA "is slow". With this patch applied, HA discovery time is decreased
to ~15s, some of which is also masked by web interface reconnect delay,
so overall subjective UX improves considerably, allowing to use HA
in auto-dicovery mode, without need to manually add devices to config
(especially with the recently added Customization Editor UI).
=> Decrease foreground scan delay for services from 5s to 2s.

netdisco/discoverables/songpal.py
List of supported devices: http://vssupport.sony.net/en_ww/device.html
P.S. the API requires parsing of the SSDP description to find the real port for communication, but I think this is a job for the backend library and not for netdisco.
=> add songpal (urn:schemas-sony-com:service:ScalarWebAPI:1) discovery

netdisco/discoverables/yeelight.py
Most likely mDNS name for the ceiling lamp (https://www.yeelight.com/en_US/product/luna). See https://github.com/home-assistant/home-assistant/issues/7793 and https://github.com/home-assistant/home-assistant/pull/9741
=> detect yeelight's ceiling lamp

netdisco/ssdp.py
A Samsung printer on my LAN appears to return both utf-8 and non utf-8 responses to SSDP queries. The non utf-8 causes ssdp.py scan() method to fail. By ignoring UnicodeDecodeError exceptions, the scan continues and even the printer is discovered because it also sends an utf-8 response.
=> Ignore non-utf8 ssdp responses in scan()

netdisco/const.py, netdisco/discoverables/deconz.py, netdisco/discoverables/philips_hue.py
This will allow auto-discovery for the new deconz component that is currently being developed at home-assistant/home-assistant#10321.
This also requires changing the Hue detection as deCONZ tries to emulate a Hue bridge.
This gist shows the differences in SSDP replies of deCONZ and a real Hue bridge: https://gist.github.com/kroimon/97c82ace08fa9787cd9e52acfba8486b
=> Allow detecting deCONZ separately from Philips Hue bridges

netdisco/discoverables/nanoleaf_aurora.py
Adds mDNS discovery for Nanoleaf Aurora lighting controllers.
=> Add Nanoleaf Aurora support

netdisco/ssdp.py
Fixed regular expression for parsing HTTP headers in order to allow 0 or more white spaces between the first colon(:) and field-content.
=> HTTP header parsing fix for SSDP

netdisco/discoverables/yeelight.py
Adds discovery of Yeelight Ceiling Light (Wifi + Bluetooth).
=> Add Yeelight Ceiling Light support

netdisco/const.py, netdisco/discoverables/tivo_dvr.py
TiVo devices expose a TCP port that allows remote control codes to be sent via the network.
This port is discoverable on MDNS as _tivo-remote._tcp.
Signed-off-by: Pat Thoyts <patthoyts@users.sourceforge.net>
=> Add support for discovery of TiVo devices providing remote control.

pylintrc
The DLNA module requires a pylint module name exception
as it does not adhere to the snake-case convention.
This might be excessive and possibly the project would prefer a specific
exception for DLNA while maintaining the snake-case convention for all
future modules. This regex will allow further upper-case and camel-case
modules to be added. But then DLNA got it so maybe we should just
be using `module-naming-style=any`?
=> Accept upper-case, snake-case and camel-case module names.

netdisco/const.py, netdisco/discoverables/freebox.py
I'm in the process of developing a new device tracker platform for Home Assistant, to support Freeboxes (servers/routers provided by the french FAI Free). This PR adds the discovery of Freeboxes through mDNS, using the service specified in the [API documentation](https://dev.freebox.fr/sdk/os/).
I've tested it on my local network, here is an example of the response I got:
```
freebox:
[{'host': '192.168.0.254',
'hostname': 'Freebox-Server.local.',
'port': 80,
'properties': {'api_base_url': '/api/',
'api_domain': '******.fbxos.fr',
'api_version': '5.0',
'device_type': 'FreeboxServer1,1',
'https_available': '1',
'https_port': '****',
'uid': '************'}}]
```
=> Add discovery of Freebox servers

README.md
`time` is imported but never used.
=> Remove unused import in example usage

netdisco/discoverables/songpal.py
It was discovered that sony bravia televisions do also use the very same
protocol for communication as "songpal" component, causing them to be added
to homeassistant although all relevant parts for them are not yet supported.
This patch adds an ignore for those devices for the time being,
at some later point the python-songpal will likely be extended to work
more properly on those devices and this may be removed.
Related to https://github.com/home-assistant/home-assistant/issues/13022
=> Ignore bravia televisions from songpal detection

netdisco/discoverables/yeelight.py
https://community.home-assistant.io/t/yeelight-led-ceiling-light-compatible-with-ha/29509/87
=> mDNS prefix of the Yeelight Smart LED Ceiling Light (Youth edition)

netdisco/discoverables/canon_printer.py
Example scan result:
```
2018-03-30 13:13:50.940639 - Found new service: canon_printer {'host': '192.168.1.40', 'port': 80, 'ssdp_description': 'http://192.168.1.40:80/Canon_basic.xml', 'name': 'MX620 series (UPnP)_4767DBFBCDEF', 'model_name': 'MX620 series', 'model_number': 'MX620 series', 'serial': 'D8492FFBCDEF', 'manufacturer': 'CANON INC.', 'udn': 'uuid:00000000-0000-1000-8000-D8492FFBCDEF'}
```
=> Added support for Canon printer

netdisco/discoverables/yeelight.py
```
>>> "yeelink-light-ceiling4_mibt72799069._miio._udp.local.".replace('yeelink-light-', '').rsplit('_', 1)[0]
'ceiling4_mibt72799069._miio.'
>>> "yeelink-light-ceiling4_mibt72799069._miio._udp.local.".replace('yeelink-light-', '').split('_', 1)[0]
'ceiling4'
>>> 
```
=> Extraction of the yeelight device type fixed

netdisco/discoverables/cambridgeaudio.py
I wrote a media_player platform module for Home-Assistant to support Cambridge Audio network audio streamers.
This is one piece of the puzzle that allows the device to be auto-discovered on the local network.
Sebastian
=> Added Cambridge Audio discoverable.

netdisco/discoverables/arduino.py
Support for network-enabled Arduino devices including ESP8266 and ESP32. Allows the detection of devices which were flashed with `esphomelib`.
```bash
$ python3 -m netdisco
Discovered devices:
arduino:
[{'host': '192.168.0.112',
'hostname': 'test.local.',
'port': 3232,
'properties': {'auth_upload': 'no',
'board': 'nodemcu-32s',
'ssh_upload': 'no',
'tcp_check': 'no'}}]
[...]
```
=> Add support for Arduino-like devices

netdisco/discoverables/homekit.py
The device name is helpful when presenting information to users, but
isn't present in the device properties. Extend info_from_entry in the
homekit discoverable to add it in.
=> Include device name in Homekit info

.travis.yml, tox.ini
There's no Python 3.7 for trusty available, and `sudo: true` is currently required for `dist: xenial` to take effect.
=> Add Python 3.7 to test matrix

setup.py
https://packaging.python.org/guides/distributing-packages-using-setuptools/#python-requires
Build failure is due to new pylint, not this change.
=> Add python_requires >= 3 to setup.py

netdisco/discoverables/yamaha.py, tests/discoverables/test_yamaha.py, tests/discoverables/yamaha_files/desc_incompatible_device.xml
=> Ensure N301 player ignored by yamaha discovery as not supported

netdisco/discoverables/igd.py
Add UPnP/IGD (Internet Gateway Device) support.
Required for https://github.com/home-assistant/home-assistant/pull/16300
=> Add UPnP/IGD discoverable

.gitignore, netdisco/ssdp.py, netdisco/util.py, requirements.txt, setup.py
Since 0.21.0, `zeroconf` replaced the usage of `netifaces` by [`ifaddr`](https://github.com/pydron/ifaddr)
Use `zeroconf.interface_addresses` to replace `util.interface_addresses` method. So that we can remove the depends of `netifaces` lib
fixes #214 
Need help to test on real device supports SSDP protocol.
=> Remove netifaces lib reference

netdisco/discoverables/__init__.py
Another thing found while working on typing stuff. I have no way to test this, but while I believe this is correct in principle, it may also not solve the issue entirely it seems to me the dict may not always contain the accessed keys. In particular, is there a `location` key in the first place, or should `Host` be used instead? And isn't the other `Port` instead of `port`?
=> Remove broken GDMDiscoverable.info_from_entry

netdisco/tellstick.py
As 1024 in tellstick is the same port as SSDP (where even utf-8 seems to crash occasionally) this intends to catch a decode error before it blows up netdisco
=> Catch potential decode error when decoding for ascii

netdisco/ssdp.py
It's out of user or developers control. We should not make it be a big deal.
=> Remove warning when SSDP can't parse description

netdisco/discoverables/openhome.py
Linn have changed the revision of the `Product` service used for device discovery of `openhome` devices in their latest firmware (http://docs.linn.co.uk/wiki/index.php/Beta:DsDavaar67:Release_Notes) without indicating that in their release notes. 
As a result Home Assistant will not be able to discover or control Linn devices running this version of the firmware.
This adds support for 'Davaar' versions advertising a `urn:av-openhome-org:service:Product:3` service.
=> Discover openhome devices with Product:3 service

netdisco/discoverables/digitalstrom.py
[digitalSTROM](https://www.digitalstrom.com/) is a swiss made home control system.
I've built a [custom component](https://github.com/lociii/homeassistant-config/tree/master/homeassistant/custom_components) for it some months ago. Control of my home is really reliable, so I wanted to go the next step and get the component integrated in Home Assistant.
Discovery result:
```
digitalstrom:
[{'host': '10.211.112.12',
'hostname': 'dss-ip.local.',
'port': 80,
'properties': {}}]
```
=> add support for digitalstrom ip servers (dss-ip)

netdisco/discoverables/songpal.py
Check for the existence of `videoScreen` service, which should be solely available on televisions.
Fixes https://community.home-assistant.io/t/platform-songpal-not-ready-yet-log-entry-linked-to-braviatv/93586 and potentially other similar misdetection issues.
=> be more strict on songpal filtering

netdisco/discoverables/enigma2.py, netdisco/lms.py, tox.ini
**Description:**
Adding enigma2 discovery.
Also fixing a type issue which is failing the build the past 2 weeks:
```
typing runtests: commands[0] | mypy netdisco tests setup.py example_service.py
netdisco/lms.py:54: note: unused 'type: ignore' comment
ERROR: InvocationError for command '/home/travis/build/home-assistant/netdisco/.tox/typing/bin/mypy netdisco tests setup.py example_service.py' (exited with code 1)
___________________________________ summary ____________________________________
ERROR:   typing: commands failed
The command "tox" exited with 1.
```
**Pull request in [home-assistant](https://github.com/home-assistant/home-assistant):** home-assistant/home-assistant#21271
=> Add support for discovering enigma2 based devices

netdisco/discoverables/sercomm.py
Sercomm manufactures a line of wired and wireless IP video
cameras that are frequently rebranded and distributed as part
of a security package by vendors such as ADT or Comcast/Xfinity.
At this point they have been pretty well reverse-engineered as well
as rooted: https://github.com/edent/Sercomm-API
=> Add support for Sercomm IP camera discovery.

netdisco/discoverables/heos.py
Add discovery of HEOS devices.
**Pull request in [home-assistant](https://github.com/home-assistant/home-assistant):** home-assistant/home-assistant#22652
=> Add discovery of HEOS devices

netdisco/mdns.py
Zeroconf now throws a BadTypeInNameException when it encounters
a bad name on the network. This causes a ServiceBrowser that
is calling ServiceInfo to collapse when trying to lookup
the service information.
=> Prevent ServiceBrowser from collapsing when encountering a BadTypeInNameException

netdisco/discovery.py, netdisco/mdns.py
- When we are already running a ServiceBrowser for services that netdisco scans for
we will already have all the answers we expect to get in the cache. By scanning
for these services again, we generate additional network traffic. Since the
known answer list was not shared between ServiceBrowsers in earlier versions
of zeroconf, we will send an empty list which will cause every services we
already have in the cache to be re-populated.
=> Add the ability to suppress mdns service scans for some services
